# Generated by Django 5.2.6 on 2025-10-03 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_init_pkg_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisepackage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='treenode',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='exercisepackage',
            name='assigned_package_file',
            field=models.CharField(blank=True, help_text='Datei aus data/uploads (Auswahl im Formular)', max_length=255, verbose_name='Paketzuordnung'),
        ),
        migrations.AddField(
            model_name='treenode',
            name='changeDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='treenode',
            name='createDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='treenode',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
