# Generated by Django 5.2.6 on 2025-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_exercisepackage_options_alter_treenode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisepackage',
            name='assigned_package_file',
        ),
        migrations.AddField(
            model_name='exercisepackage',
            name='packageAssignment',
            field=models.FilePathField(blank=True, match='.+\\.(zip|xml|json)$', max_length=512, null=True, path='K:\\PyCharm-Projekte\\memorytrainer\\data\\uploads', verbose_name='Paketzurordnung'),
        ),
    ]
