# Generated by Django 5.2.6 on 2025-10-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_remove_exercisepackage_assigned_package_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisepackage',
            name='packageAssignment',
            field=models.CharField(blank=True, help_text='Dateiname der zugeordneten Datei (im assigned-packages)', max_length=255, null=True),
        ),
    ]
