# Generated by Django 5.1.5 on 2025-02-15 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='memorytrainer.treenode')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=255)),
                ('packageDescription', models.TextField()),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
                ('changeDate', models.DateField(default=django.utils.timezone.now)),
                ('treeNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_packages', to='memorytrainer.treenode')),
            ],
        ),
    ]
