"""
Django settings for memorytrainer project.
Generated by 'django-admin startproject' using Django 5.1.5.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DATA_ROOT = Path(os.environ.get("MEMORYTRAINER_DATA_ROOT", str(BASE_DIR.parent / "data")))

UPLOADS_DIR = DATA_ROOT / "uploads"
ASSIGNED_PACKAGES_DIR = DATA_ROOT / "assigned-packages"

# erzeugen, falls fehlend
UPLOADS_DIR.mkdir(parents=True, exist_ok=True)
ASSIGNED_PACKAGES_DIR.mkdir(parents=True, exist_ok=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zkqox2%at$d80#$vbn^im7lmz%_7*%lwn()h$tox+!+4nnv2%k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []  # für Dev okay; sonst z.B. ["localhost","127.0.0.1"]

# Application definition
INSTALLED_APPS = [
    'packages.apps.PackagesConfig',
    'landing',            # deine Landing-Seiten-App
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'memorytrainer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # zusätzlich zu app-templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'memorytrainer.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'db.sqlite3'),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'de-de'          # <— optional, aber sinnvoll
TIME_ZONE = 'Europe/Berlin'      # <— optional, aber sinnvoll
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # hier kommen DEINE Dateien rein (CSS, JS, Icons etc.)
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # wird nur beim collectstatic verwendet

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/pakete/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
# optional:
LOGIN_URL = '/accounts/login/'

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "noreply@example.com"

#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.yourprovider.tld"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "smtp-user"
EMAIL_HOST_PASSWORD = "smtp-password"
#DEFAULT_FROM_EMAIL = "noreply@deine-domain.tld"
