"""
Django settings for memorytrainer project.
Generated by 'django-admin startproject' using Django 5.1.5.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DATA_ROOT = Path(os.environ.get("MEMORYTRAINER_DATA_ROOT", str(BASE_DIR.parent / "data")))

UPLOADS_DIR = DATA_ROOT / "uploads"
ASSIGNED_PACKAGES_DIR = DATA_ROOT / "assigned-packages"
UPLOADED_PACKAGES_DIR = DATA_ROOT / "UploadedPackages"

# erzeugen, falls fehlend
UPLOADS_DIR.mkdir(parents=True, exist_ok=True)
ASSIGNED_PACKAGES_DIR.mkdir(parents=True, exist_ok=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("MEMORYTRAINER_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("MEMORYTRAINER_DEBUG", "true").lower() in ("1", "true", "yes")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "development-only-memorytrainer-key"
    else:
        raise RuntimeError("MEMORYTRAINER_SECRET_KEY must be set in production")

ALLOWED_HOSTS = [host.strip() for host in os.environ.get(
    "MEMORYTRAINER_ALLOWED_HOSTS", "localhost,127.0.0.1"
).split(",") if host.strip()]
FORCE_SCRIPT_NAME = os.environ.get("MEMORYTRAINER_SCRIPT_NAME", "").rstrip("/") or None
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ.get(
    "MEMORYTRAINER_CSRF_TRUSTED_ORIGINS", ""
).split(",") if origin.strip()]
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_PATH = f"{FORCE_SCRIPT_NAME}/" if FORCE_SCRIPT_NAME else "/"
CSRF_COOKIE_PATH = SESSION_COOKIE_PATH
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if os.environ.get("MEMORYTRAINER_TRUST_PROXY_SSL", "false").lower() in ("1", "true", "yes")
    else None
)

# Application definition
INSTALLED_APPS = [
    'packages.apps.PackagesConfig',
    'landing',            # deine Landing-Seiten-App
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'memorytrainer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # zusätzlich zu app-templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'memorytrainer.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get("MEMORYTRAINER_DB_PATH", str(BASE_DIR / 'db.sqlite3')),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'de-de'          # <— optional, aber sinnvoll
TIME_ZONE = 'Europe/Berlin'      # <— optional, aber sinnvoll
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # hier kommen DEINE Dateien rein (CSS, JS, Icons etc.)
]

STATIC_ROOT = Path(os.environ.get("MEMORYTRAINER_STATIC_ROOT", str(BASE_DIR / "staticfiles")))

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'landing:pakete'
LOGOUT_REDIRECT_URL = 'login_register'
LOGIN_URL = 'login_register'

EMAIL_BACKEND = os.environ.get(
    "MEMORYTRAINER_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend" if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.environ.get("MEMORYTRAINER_FROM_EMAIL", "noreply@roland-prinz.de")
EMAIL_HOST = os.environ.get("MEMORYTRAINER_EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("MEMORYTRAINER_EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("MEMORYTRAINER_EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
EMAIL_HOST_USER = os.environ.get("MEMORYTRAINER_EMAIL_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("MEMORYTRAINER_EMAIL_PASSWORD", "")
